# Generated by Django 3.2 on 2021-04-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210420_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='Total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='content_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packages',
            name='pages',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packages',
            name='design_customization',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='packages',
            name='responsive_design',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='packages',
            name='revisions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packages',
            name='source_code',
            field=models.BooleanField(default=False),
        ),
    ]
