# Generated by Django 3.2 on 2021-05-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210420_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='image',
            new_name='imgUrl',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='preview',
            new_name='url',
        ),
    ]
